"""db setup

Revision ID: 5c30a5c1c80d
Revises: 
Create Date: 2026-01-10 21:54:30.370610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c30a5c1c80d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('posts', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('average_likes', sa.Float(), nullable=True),
    sa.Column('average_comments', sa.Float(), nullable=True),
    sa.Column('posting_frequency', sa.String(length=50), nullable=True),
    sa.Column('last_post_days', sa.Integer(), nullable=True),
    sa.Column('growth_potential', sa.String(length=20), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('contacted', sa.Boolean(), nullable=True),
    sa.Column('contacted_date', sa.DateTime(), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('converted_to_client', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_analyzed_at'), 'analysis_history', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_history_contacted'), 'analysis_history', ['contacted'], unique=False)
    op.create_index(op.f('ix_analysis_history_opportunity_score'), 'analysis_history', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_analysis_history_username'), 'analysis_history', ['username'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('instagram_username', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_username', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_area'), 'businesses', ['area'], unique=False)
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_instagram_username'), 'businesses', ['instagram_username'], unique=False)
    op.create_index(op.f('ix_businesses_pincode'), 'businesses', ['pincode'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_area', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('min_followers', sa.Integer(), nullable=True),
    sa.Column('max_followers', sa.Integer(), nullable=True),
    sa.Column('min_opportunity_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('profiles_found', sa.Integer(), nullable=True),
    sa.Column('usernames_to_monitor', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_business_category'), 'crawl_jobs', ['business_category'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_is_active'), 'crawl_jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_location_city'), 'crawl_jobs', ['location_city'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_pincode'), 'crawl_jobs', ['pincode'], unique=False)
    op.create_table('instagram_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('first_crawled', sa.DateTime(), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_profiles_username'), 'instagram_profiles', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_profiles_username'), table_name='instagram_profiles')
    op.drop_table('instagram_profiles')
    op.drop_index(op.f('ix_crawl_jobs_pincode'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_location_city'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_is_active'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_business_category'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_businesses_pincode'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_instagram_username'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_area'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_analysis_history_username'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_opportunity_score'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_contacted'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_analyzed_at'), table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
